### ISSUE TITLE
是否支持上拉加载更多

### ISSUE THREAD

**Issue by jyh149129** [CaMnter/EasyRecyclerView#1]

**Comment by CaMnter** [comment]
@jyh149129 上拉加载的话，目前没支持，这个库子是便捷式开发Apdater，RecyclerView的话也只是配置一下参数，没做修改。
可以推荐你用一个1.https://github.com/CaMnter/EasyGank/blob/master/app/src/main/java/com/camnter/easygank/widget/MultiSwipeRefreshLayout.java
完成上拉和下拉。
2.上拉的话可以做简单一些，判断到底部请求数据，当然这不是最好的，(｡>﹏<｡)

**Comment by jyh149129** [comment]
谢谢
