### ISSUE TITLE
问一个小问题？

### ISSUE THREAD

**Issue by baoyachi** [CaMnter/EasyRecyclerView#2]
请问如何设置展示内容为手机三星手机背景？我一般设置背景就是一般手机的，看到你可以设置为三星手机的背景，请问您是如何操作的？能分享下吗

![2016-06-06 9 58 02](https://cloud.githubusercontent.com/assets/10433001/15810079/5adb887e-2bcd-11e6-8a2b-f285cfaa56c9.png)

**Comment by CaMnter** [comment]
@baoyachi 有个应用，我忘了叫什么了，好久没用了，手机里应用很多...
